version: "3.3"
services:  
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  backend:
    image: 860867269765.dkr.ecr.us-east-1.amazonaws.com/serpent-tracker-backend:staging
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env-staging
    ports:
    - 8888:80
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}

volumes:
  app-db-data:
