"""Add imageurl to snake model

Revision ID: 010ecb889895
Revises: 6ec2af26fe5b
Create Date: 2020-05-09 10:44:52.279412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010ecb889895'
down_revision = '6ec2af26fe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('imageurl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'imageurl')
    # ### end Alembic commands ###
