"""add pre_lay field to Shed model

Revision ID: 0274d7e20c4b
Revises: 56ed81901df3
Create Date: 2020-04-30 12:02:26.367928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0274d7e20c4b'
down_revision = '56ed81901df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shed', sa.Column('pre_lay', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shed', 'pre_lay')
    # ### end Alembic commands ###
