"""Add scientific and common name fields to Snake model

Revision ID: 22dd2a3da174
Revises: 9ffa1630b9be
Create Date: 2020-04-28 10:36:57.184599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dd2a3da174'
down_revision = '9ffa1630b9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('common_name', sa.String(), nullable=True))
    op.add_column('snake', sa.Column('scientific_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'scientific_name')
    op.drop_column('snake', 'common_name')
    # ### end Alembic commands ###
