"""Add visual genes list/array column to Snake model

Revision ID: 6b146b6c18a8
Revises: 9536d8807195
Create Date: 2020-04-28 10:16:28.655207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b146b6c18a8'
down_revision = '9536d8807195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('visual_genes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'visual_genes')
    # ### end Alembic commands ###
