"""Add shed model

Revision ID: 845437c1292a
Revises: e10000ed27c6
Create Date: 2020-04-28 17:55:26.494081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845437c1292a'
down_revision = 'e10000ed27c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('shed_date', sa.DateTime(), nullable=True),
    sa.Column('snake_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snake_id'], ['snake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shed_id'), 'shed', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shed_id'), table_name='shed')
    op.drop_table('shed')
    # ### end Alembic commands ###
