"""Add excretion model

Revision ID: 8a020dbf530e
Revises: db3e7229d936
Create Date: 2020-04-28 19:48:14.601573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a020dbf530e'
down_revision = 'db3e7229d936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excretion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urates', sa.Boolean(), nullable=True),
    sa.Column('feces', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('excretion_date', sa.DateTime(), nullable=True),
    sa.Column('snake_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['snake_id'], ['snake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excretion_id'), 'excretion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excretion_id'), table_name='excretion')
    op.drop_table('excretion')
    # ### end Alembic commands ###
