"""add notes field to cycle model

Revision ID: 8efede552a27
Revises: 0274d7e20c4b
Create Date: 2020-04-30 12:28:20.685154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efede552a27'
down_revision = '0274d7e20c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle', 'notes')
    # ### end Alembic commands ###
