"""Add produced_by column to Snake model

Revision ID: 9536d8807195
Revises: a185dfc6c060
Create Date: 2020-04-28 09:26:48.814151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9536d8807195'
down_revision = 'a185dfc6c060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('produced_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'produced_by')
    # ### end Alembic commands ###
