"""Add het_genes column to Snake model

Revision ID: 9ffa1630b9be
Revises: 6b146b6c18a8
Create Date: 2020-04-28 10:19:32.466002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffa1630b9be'
down_revision = '6b146b6c18a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('het_genes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'het_genes')
    # ### end Alembic commands ###
