"""Add column hatch_date to Snake model

Revision ID: e47796461a4d
Revises: 680ce6942c7e
Create Date: 2020-04-27 22:05:21.289590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47796461a4d'
down_revision = '680ce6942c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snake', sa.Column('hatch_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snake', 'hatch_date')
    # ### end Alembic commands ###
