
name: Test PR

on:
  pull_request:
    paths-ignore:
    - "README.md"
    - "frontend/**"


jobs:
  backend-testing:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create ENV File
      run: mv .env.example .env
    - name: Run Test Shell Script
      run: sh ./scripts/test.sh
  # build-image:
  #   name: Build & Push PR Image To ECR
  #   runs-on: ubuntu-latest
  #   needs: [backend-testing]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Login to ECR
  #     id: ecr
  #     uses: jwalton/gh-ecr-login@v1
  #     with:
  #       access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       region: us-east-1
  #   - name: Build PR Image Tag
  #     run: docker build --tag ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/serpent-tracker-backend:pr-$(echo ${GITHUB_SHA} | cut -c1-8) -f backend/backend.dockerfile ./backend
  #   - name: Push Backend PR Commit Tag Image to ECR
  #     run: docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/serpent-tracker-backend:pr-$(echo ${GITHUB_SHA} | cut -c1-8)